-- COMBINACAO DAS TABELAS 

DROP TABLE IF EXISTS CYCLISTIC_2022

-- COMBINACAO DAS TABELAS DE JANEIRO A DEZEMBRO DE 2022 DA EMPRESA CYCLISTIC

CREATE TABLE 2022_CYCLISTIC AS (
SELECT * FROM JANUARY
UNION ALL
SELECT * FROM FEBRUARY
UNION ALL
SELECT * FROM MARCH
UNION ALL
SELECT * FROM APRIL
UNION ALL
SELECT * FROM MAY
UNION ALL
SELECT * FROM JUNE
UNION ALL
SELECT * FROM JULY
UNION ALL
SELECT * FROM AUGUST
UNION ALL
SELECT * FROM SEPTEMBER
UNION ALL
SELECT * FROM OCTOBER
UNION ALL
SELECT * FROM NOVEMBER
UNION ALL
SELECT * FROM DECEMBER
);

select * from 2022_cyclistic;

select count(*) from 2022_CYCLISTIC;
